### PR TITLE
RawSegment and binary codec

### PR DESCRIPTION
**Pull request by wemrysi**

### CODE REVIEW

**Comment by wemrysi** [comment]
omg, a build!

**Comment by alissapajer** [comment]
Can you add `better-monadic-for` to all the projects?

**Review by alissapajer — CHANGES_REQUESTED** [review]
Just missing `better-monadic-for` - other than that 👍

**Review by alissapajer — APPROVED** [review]

**Comment by wemrysi** [comment]
[ch7174]

**Pull request merged**
